language: python
dist: xenial
python:
  - "3.7"
# Install dependencies
install:
  - pip install -r requirements.txt
# Include MySQL
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS mad; CREATE TABLE [IF NOT EXISTS] cv_term_vw (id int, name varchar(255))'
script: 
  - python test_base.py TestErrors TestDiagnostics
  - pylint --disable=C,W,R mad_responder.py
